# Generated by Django 4.2.5 on 2023-09-21 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=datetime.date(2023, 9, 21), verbose_name='Added Date'),
        ),
    ]
