# Generated by Django 4.2.5 on 2023-09-21 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 16, 24, 31, 595645, tzinfo=datetime.timezone.utc), verbose_name='Added Date'),
        ),
    ]
