# Generated by Django 4.2.5 on 2023-09-21 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_added_date_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='joined_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 9, 21, 16, 35, 54, 722568, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 16, 35, 54, 722568, tzinfo=datetime.timezone.utc), verbose_name='Added Date'),
        ),
    ]
