# Generated by Django 4.2.5 on 2023-09-21 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_added_date_alter_seller_joined_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='watch',
        ),
        migrations.AddField(
            model_name='client',
            name='watch',
            field=models.ManyToManyField(to='products.video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 17, 0, 1, 953891, tzinfo=datetime.timezone.utc), verbose_name='Added Date'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 17, 0, 1, 953891, tzinfo=datetime.timezone.utc), verbose_name='Joined Date'),
        ),
    ]
