# Generated by Django 4.2.5 on 2023-09-22 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_video_watch_client_watch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 21, 38, 12, 701806, tzinfo=datetime.timezone.utc), verbose_name='Added Date'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 21, 38, 12, 701806, tzinfo=datetime.timezone.utc), verbose_name='Joined Date'),
        ),
    ]
