# Generated by Django 4.2.5 on 2023-09-25 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_options_alter_product_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 18, 28, 8, 669534, tzinfo=datetime.timezone.utc), verbose_name='Added Date'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 18, 28, 8, 669534, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Joined Date'),
        ),
    ]
